apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  srcds-token: {{ required "A valid SRCDS token is required!" .Values.application.secrets.srcdstoken | b64enc }}
  srcds-rconpw: {{ .Values.application.secrets.srcdsrconpw | b64enc }}
  srcds-pw: {{ .Values.application.secrets.srcdspw | b64enc }}
